apiVersion: v1
kind: Service
metadata:
  name: api
  labels:
    name: api
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 3000
    targetPort: 3000
  selector:
    name: heroes-api
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name:  heroes-api-deploy
  labels:
    name:  heroes-api
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        name:  heroes-api
    spec:
      containers:
      - image: chzbrgr71/rating-api:latest
        name:  heroes-api-cntnr
        resources:
          requests:
            cpu: "20m"
            memory: "55M"
        env:
        - name:  MONGODB_URI
          value:  mongodb://db:27017/webratings
        ports:
        - containerPort:  3000
          name:  heroes-api
        imagePullPolicy: Always
      restartPolicy: Always